{
 "title": "Network Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Signal Level",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  signal_level\nFROM wifi_experience.ssid\nwhere mac = 'B8:27:EB:E8:6E:F8'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Signal level vs Channel History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  signal_level,\n  channel\nFROM realtime_view\nwhere mac = 'B8:27:EB:E8:6E:F8'\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Network Encryption Protocols",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT network_name, encryption from wifi_experience.ssid where encryption != 'WPA2' AND mac = 'B8:27:EB:E8:6E:F8' group by ssid.network_name, ssid.encryption;"
    }
   ]
  },
  {
   "title": "Average Signal Level",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  signal_level\nFROM wifi_experience.ssid\nwhere mac = 'B8:27:EB:E8:6E:F8'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Signal Level",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  signal_level\nFROM wifi_experience.ssid\nwhere mac = 'B8:27:EB:E8:6E:F8'\nORDER BY 1"
    }
   ]
  }
 ]
}